### ISSUE TITLE
Inherit CBMaterialTabbarItem

### ISSUE THREAD

**Issue by ushehri** [cbangchen/CBMDTabbarController#2]
Hi, 

I am glad to use your custom tabBar. I did the installation part as you mentioned and I keep getting 
fetal error: Items must inherit CBMaterialTabbarItem ! 

can't solve this issue I tried so hard

**Comment by cbangchen** [comment]
I'm sorry to see you being troubled by this problem. Let me help you to solve this problem. 

Click the main.storyboard, and then you can see storyboard like this.

<img width="468" alt="2017-08-20 11 26 47" src="https://user-images.githubusercontent.com/11977680/29496154-87f71844-8592-11e7-898c-928d0cd43891.png">

Then you chose can one of the items and click it .

<img width="320" alt="2017-08-20 11 27 20" src="https://user-images.githubusercontent.com/11977680/29496170-cf950c38-8592-11e7-8a05-f5c6019a908c.png">

<img width="701" alt="2017-08-20 11 27 59" src="https://user-images.githubusercontent.com/11977680/29496177-f2a0f976-8592-11e7-8e60-055b3441d8dc.png">

As you can see, you can change the class object that you want this item to inherit in this page. 

Please fix your project by using this solution and feel free to let me know if you have any problem.

Thx for your attention and have a nice day.

**Comment by ushehri** [comment]
Hi cbangchen , 

I have done that Thanks for your help , It turned out the there was one tabBar Item did not correctly changed its class. I am really sorry to open that issue it was completely my mistake.

Thanks for your help

**Comment by cbangchen** [comment]
I am happy that you have already solved this problem.  Because of your help, I know that the document I have wrote before can be really confusing. I should fix it in the next few days. Anyway, thx again for your attention and please let me know if you have any other questions.
